version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    # Aqui você define os caminhos para os arquivos de manifesto do Poetry e para os arquivos de bloqueio de versão, se aplicável
    # Certifique-se de substituir `<diretório do projeto>` pelo caminho real
    directory: "/"
    target-branches:
      - "master"
    # Aqui você define quais tipos de atualizações permitir
    updates:
      - package-ecosystem: "pip"
        directory: "/"
        schedule:
          interval: "daily"
        # Aqui você permite atualizações para patch releases e minor releases
        # Bloqueia atualizações para major releases
        labels:
          - "patch"
          - "minor"
        # Aqui você pode especificar pacotes para ignorar, se necessário
        ignore:
          - dependency-name: "pytest"
            versions: [">=6.0.0a1, <7.0.0"]
